# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - bulmabasic

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.10' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    defaults:
      run:
        working-directory: ./api

    runs-on: ubuntu-latest #-- GitHub hosted runner: the list are :
    steps:                 #-- ubuntu, windows, macos
      - name: Checkout repository
        uses: actions/checkout@v4 #-- checkout the branch

      - name: Setup Python version
        uses: actions/setup-python@v1 #-- setup python on runner
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: | #-- 'run' is used to run commands on environment
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt #-- run the file of requirements

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment 
        run: zip release.zip ./* -r       #-- package the project

      - name: Upload artifact for deployment job 
        uses: actions/upload-artifact@v3 #-- upload the project to be deployed
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: 'Deploy to Azure Functions' 
        uses: Azure/functions-action@v1 #-- connect to cloud and deploy
        id: deploy-to-function
        with:
          app-name: 'bulmabasic'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}